[package]
name = "free_sdm"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
actix-web = "4.3.1"
colored = "2.0.4"
local-ip-address = "0.5.3"
rand = "0.8.5"
simulate = "0.3.0"
text_io = "0.1.12"
